de_ai_agent:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "../data/fifa.duckdb"
      schema: SILVER
      threads: 4

    prod:
      type: duckdb
      path: "../data/fifa_prod.duckdb"
      schema: SILVER
      threads: 4
