-- =============================================================
-- DE AI Agent — Snowflake Setup (idempotent)
-- Run as SYSADMIN or ACCOUNTADMIN once per environment
-- =============================================================

-- ── Warehouse ─────────────────────────────────────────────────
CREATE WAREHOUSE IF NOT EXISTS DE_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND   = 60
    AUTO_RESUME    = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'DE AI Agent — shared warehouse';

-- ── Database ──────────────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS DE_AI_AGENT_DEV;
CREATE DATABASE IF NOT EXISTS DE_AI_AGENT_PROD;

-- ── Schemas (medallion layers) per environment ────────────────
-- DEV
CREATE SCHEMA IF NOT EXISTS DE_AI_AGENT_DEV.BRONZE;   -- raw ingestion
CREATE SCHEMA IF NOT EXISTS DE_AI_AGENT_DEV.SILVER;   -- staged / cleaned
CREATE SCHEMA IF NOT EXISTS DE_AI_AGENT_DEV.GOLD;     -- marts / serving

-- PROD
CREATE SCHEMA IF NOT EXISTS DE_AI_AGENT_PROD.BRONZE;
CREATE SCHEMA IF NOT EXISTS DE_AI_AGENT_PROD.SILVER;
CREATE SCHEMA IF NOT EXISTS DE_AI_AGENT_PROD.GOLD;

-- ── Roles ─────────────────────────────────────────────────────
CREATE ROLE IF NOT EXISTS DE_INGEST_ROLE;
CREATE ROLE IF NOT EXISTS DE_TRANSFORM_ROLE;
CREATE ROLE IF NOT EXISTS DE_SERVING_ROLE;

-- Role hierarchy: SYSADMIN owns all custom roles
GRANT ROLE DE_INGEST_ROLE    TO ROLE SYSADMIN;
GRANT ROLE DE_TRANSFORM_ROLE TO ROLE SYSADMIN;
GRANT ROLE DE_SERVING_ROLE   TO ROLE SYSADMIN;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE DE_WH TO ROLE DE_INGEST_ROLE;
GRANT USAGE ON WAREHOUSE DE_WH TO ROLE DE_TRANSFORM_ROLE;
GRANT USAGE ON WAREHOUSE DE_WH TO ROLE DE_SERVING_ROLE;

-- ── Ingest role: write to BRONZE only ────────────────────────
GRANT USAGE ON DATABASE DE_AI_AGENT_DEV  TO ROLE DE_INGEST_ROLE;
GRANT USAGE ON DATABASE DE_AI_AGENT_PROD TO ROLE DE_INGEST_ROLE;
GRANT USAGE ON SCHEMA DE_AI_AGENT_DEV.BRONZE  TO ROLE DE_INGEST_ROLE;
GRANT USAGE ON SCHEMA DE_AI_AGENT_PROD.BRONZE TO ROLE DE_INGEST_ROLE;
GRANT CREATE TABLE, INSERT, UPDATE ON SCHEMA DE_AI_AGENT_DEV.BRONZE  TO ROLE DE_INGEST_ROLE;
GRANT CREATE TABLE, INSERT, UPDATE ON SCHEMA DE_AI_AGENT_PROD.BRONZE TO ROLE DE_INGEST_ROLE;

-- ── Transform role: read BRONZE, write SILVER + GOLD ─────────
GRANT USAGE ON DATABASE DE_AI_AGENT_DEV  TO ROLE DE_TRANSFORM_ROLE;
GRANT USAGE ON DATABASE DE_AI_AGENT_PROD TO ROLE DE_TRANSFORM_ROLE;
-- Bronze read
GRANT USAGE ON SCHEMA DE_AI_AGENT_DEV.BRONZE  TO ROLE DE_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA DE_AI_AGENT_PROD.BRONZE TO ROLE DE_TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DE_AI_AGENT_DEV.BRONZE  TO ROLE DE_TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DE_AI_AGENT_PROD.BRONZE TO ROLE DE_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DE_AI_AGENT_DEV.BRONZE  TO ROLE DE_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DE_AI_AGENT_PROD.BRONZE TO ROLE DE_TRANSFORM_ROLE;
-- Silver + Gold write
GRANT USAGE ON SCHEMA DE_AI_AGENT_DEV.SILVER  TO ROLE DE_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA DE_AI_AGENT_DEV.GOLD    TO ROLE DE_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA DE_AI_AGENT_PROD.SILVER TO ROLE DE_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA DE_AI_AGENT_PROD.GOLD   TO ROLE DE_TRANSFORM_ROLE;
GRANT CREATE TABLE, INSERT, UPDATE, DELETE, TRUNCATE ON SCHEMA DE_AI_AGENT_DEV.SILVER  TO ROLE DE_TRANSFORM_ROLE;
GRANT CREATE TABLE, INSERT, UPDATE, DELETE, TRUNCATE ON SCHEMA DE_AI_AGENT_DEV.GOLD    TO ROLE DE_TRANSFORM_ROLE;
GRANT CREATE TABLE, INSERT, UPDATE, DELETE, TRUNCATE ON SCHEMA DE_AI_AGENT_PROD.SILVER TO ROLE DE_TRANSFORM_ROLE;
GRANT CREATE TABLE, INSERT, UPDATE, DELETE, TRUNCATE ON SCHEMA DE_AI_AGENT_PROD.GOLD   TO ROLE DE_TRANSFORM_ROLE;

-- ── Serving role: read GOLD only ─────────────────────────────
GRANT USAGE ON DATABASE DE_AI_AGENT_DEV  TO ROLE DE_SERVING_ROLE;
GRANT USAGE ON DATABASE DE_AI_AGENT_PROD TO ROLE DE_SERVING_ROLE;
GRANT USAGE ON SCHEMA DE_AI_AGENT_DEV.GOLD  TO ROLE DE_SERVING_ROLE;
GRANT USAGE ON SCHEMA DE_AI_AGENT_PROD.GOLD TO ROLE DE_SERVING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DE_AI_AGENT_DEV.GOLD  TO ROLE DE_SERVING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DE_AI_AGENT_PROD.GOLD TO ROLE DE_SERVING_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DE_AI_AGENT_DEV.GOLD  TO ROLE DE_SERVING_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DE_AI_AGENT_PROD.GOLD TO ROLE DE_SERVING_ROLE;

-- ── Bronze tables (raw landing + dead letter) ─────────────────
-- Sales (CSV source)
CREATE TABLE IF NOT EXISTS DE_AI_AGENT_DEV.BRONZE.RAW_SALES (
    _row_id         VARCHAR(64)    NOT NULL,  -- SHA256 of source row
    _source_file    VARCHAR(500),
    _ingested_at    TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    _batch_id       VARCHAR(64),
    row_id          VARCHAR(50),
    order_id        VARCHAR(50),
    order_date      VARCHAR(20),
    ship_date       VARCHAR(20),
    ship_mode       VARCHAR(50),
    customer_id     VARCHAR(50),
    customer_name   VARCHAR(200),
    segment         VARCHAR(50),
    country         VARCHAR(100),
    city            VARCHAR(100),
    state           VARCHAR(100),
    postal_code     VARCHAR(20),
    region          VARCHAR(50),
    product_id      VARCHAR(50),
    category        VARCHAR(100),
    sub_category    VARCHAR(100),
    product_name    VARCHAR(500),
    sales           VARCHAR(50),
    quantity        VARCHAR(20),
    discount        VARCHAR(20),
    profit          VARCHAR(50)
);

-- Weather (API source)
CREATE TABLE IF NOT EXISTS DE_AI_AGENT_DEV.BRONZE.RAW_WEATHER (
    _row_id       VARCHAR(64)   NOT NULL,
    _ingested_at  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _batch_id     VARCHAR(64),
    date          VARCHAR(20),
    latitude      VARCHAR(20),
    longitude     VARCHAR(20),
    temperature_max  VARCHAR(20),
    temperature_min  VARCHAR(20),
    precipitation    VARCHAR(20),
    wind_speed_max   VARCHAR(20),
    weather_code     VARCHAR(10)
);

-- Products (SQLite/DB source)
CREATE TABLE IF NOT EXISTS DE_AI_AGENT_DEV.BRONZE.RAW_PRODUCTS (
    _row_id         VARCHAR(64)   NOT NULL,
    _ingested_at    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _batch_id       VARCHAR(64),
    _extracted_at   TIMESTAMP_NTZ,
    product_id      VARCHAR(50),
    product_name    VARCHAR(500),
    category        VARCHAR(100),
    sub_category    VARCHAR(100),
    unit_cost       VARCHAR(20),
    supplier        VARCHAR(200),
    in_stock        VARCHAR(10),
    last_updated    VARCHAR(30)
);

-- Dead letter (contract violations from all sources)
CREATE TABLE IF NOT EXISTS DE_AI_AGENT_DEV.BRONZE.DEAD_LETTER (
    _dl_id          VARCHAR(64)    NOT NULL DEFAULT gen_random_uuid()::VARCHAR,
    _ingested_at    TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    _batch_id       VARCHAR(64),
    _source         VARCHAR(100),  -- 'sales' | 'weather' | 'products'
    _error_type     VARCHAR(200),  -- Pydantic validation error type
    _error_detail   VARCHAR(2000),
    _raw_payload    VARIANT        -- original row as JSON for reprocessing
);

-- Mirror tables for PROD
CREATE TABLE IF NOT EXISTS DE_AI_AGENT_PROD.BRONZE.RAW_SALES      LIKE DE_AI_AGENT_DEV.BRONZE.RAW_SALES;
CREATE TABLE IF NOT EXISTS DE_AI_AGENT_PROD.BRONZE.RAW_WEATHER    LIKE DE_AI_AGENT_DEV.BRONZE.RAW_WEATHER;
CREATE TABLE IF NOT EXISTS DE_AI_AGENT_PROD.BRONZE.RAW_PRODUCTS   LIKE DE_AI_AGENT_DEV.BRONZE.RAW_PRODUCTS;
CREATE TABLE IF NOT EXISTS DE_AI_AGENT_PROD.BRONZE.DEAD_LETTER    LIKE DE_AI_AGENT_DEV.BRONZE.DEAD_LETTER;

-- ── Watermark table (tracks incremental extraction state) ─────
CREATE TABLE IF NOT EXISTS DE_AI_AGENT_DEV.BRONZE.INGESTION_WATERMARKS (
    source_name      VARCHAR(100) NOT NULL,
    last_loaded_at   TIMESTAMP_NTZ,
    last_batch_id    VARCHAR(64),
    rows_loaded      INTEGER,
    updated_at       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT pk_watermarks PRIMARY KEY (source_name)
);
CREATE TABLE IF NOT EXISTS DE_AI_AGENT_PROD.BRONZE.INGESTION_WATERMARKS
    LIKE DE_AI_AGENT_DEV.BRONZE.INGESTION_WATERMARKS;

-- Seed watermarks
INSERT INTO DE_AI_AGENT_DEV.BRONZE.INGESTION_WATERMARKS (source_name, last_loaded_at, rows_loaded)
    SELECT 'sales',    NULL, 0 WHERE NOT EXISTS (SELECT 1 FROM DE_AI_AGENT_DEV.BRONZE.INGESTION_WATERMARKS WHERE source_name = 'sales');
INSERT INTO DE_AI_AGENT_DEV.BRONZE.INGESTION_WATERMARKS (source_name, last_loaded_at, rows_loaded)
    SELECT 'weather',  NULL, 0 WHERE NOT EXISTS (SELECT 1 FROM DE_AI_AGENT_DEV.BRONZE.INGESTION_WATERMARKS WHERE source_name = 'weather');
INSERT INTO DE_AI_AGENT_DEV.BRONZE.INGESTION_WATERMARKS (source_name, last_loaded_at, rows_loaded)
    SELECT 'products', NULL, 0 WHERE NOT EXISTS (SELECT 1 FROM DE_AI_AGENT_DEV.BRONZE.INGESTION_WATERMARKS WHERE source_name = 'products');
